apiVersion: v1
kind: Service
metadata:
  name: mini-cassandra-loadgen
  labels:
    app: mini-cassandra-loadgen
spec:
  selector:
    app: mini-cassandra-loadgen
  ports:
    - name: http
      port: 8080
      targetPort: http

